config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'homes#top'

  get 'top' => 'homes#top'
  post 'back' => 'homes#back'
  post 'create' => 'homes#create'
  post 'confirm' => 'homes#confirm'
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resource :admin_user, only: [:new, :create, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/userinfo.rb
class Userinfo < ApplicationRecord
    #姓（漢字）,名（漢字）,せい（ふりがな）,めい（ふりがな）
    validates :name_first,
              :name_last,
              :name_first_read,
              :name_last_read,
              presence: { message: 'が入力されていません。' }
    #性別,生年月日
    validates :sex,
              :birthday,
              presence: { message: 'が選択されていません。' } 
    #郵便番号
    validates :postnumber, presence: { message: 'が入力されていません。' } 
    validates :postnumber, format: { with: /\A\d{3}[-]?\d{4}\z/, message: 'は半角英数字で正しい桁数で入力してください。'} 
    #都道府県
    validates :prefecture, presence: { message: 'が選択されていません。' } 
    #市区町村名,番地名
    validates :municipalities,
              :street,
              presence: { message: 'が入力されていません。' }

    #PCメールアドレス,携帯メールアドレス          
    validates :mail_pc_or_pass, presence: { message: 'を入力してください。' }
    validates :mail_pc, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, if: :mail_pc_presence?
    validates :mail_pass, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, if: :mail_pass_presence?

    #調査経験回数
    validates :survey_experience, presence: { message: 'が選択されていません。' } 
    #希望する調査
    validates :desire_survey_check, presence: { message: 'が選択されていません。' }  
    #車の保有について,認知経路
    validates :possession_car,
              :cognitive_pathway,
              presence: { message: 'が選択されていません。' } 
    #認知経路
    validates :cognitive_pathway, presence: { message: 'が選択されていません。' } 
    #パスワード
    validates :password, presence: { message: 'が入力されていません。' } 
    validates :password, format: { with: /\A^[0-9a-zA-Z]{8,}+$\z/, message: 'は半角英数字のみで8文字以上で設定してください。'}
    
    #PCメールアドレスか携帯メールアドレスのどちらかが入力されているか
    private
    def mail_pc_or_pass
        mail_pc.presence or 
        mail_pass.presence
    end

    #PCメールアドレスが入力されているか
    private
    def mail_pc_presence?
        mail_pc.presence
    end    

    #携帯メールアドレスが入力されているか
    private
    def mail_pass_presence?
        mail_pass.presence
    end   

    #希望する調査のチェックボックスのどれかにチェックされているか
    private
    def desire_survey_check
        traffic_survey.presence or 
        driving_survey.presence or
        bus_survey.presence or
        questionnaire_distribution.presence or
        interview_survey.presence or
        visit_survey.presence or
        undercover_investigation.presence or
        office_staff.presence  
    end
 end

app/controllers/admin_users_controller.rb
# coding: UTF-8
class AdminUsersController < ApplicationController
require 'csv'

  def new
   @user = AdminUser.new
   @userinfonew = Userinfo.all
  end

  def create
   user =AdminUser.new(admin_user_params)
   if user.save
     session[:user_id] = user.id
     redirect_to admin_user_path
   else
    render :new
   end
  end

  def show
   @userinfocsv = Userinfo.all
   @userinfo = Userinfo.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_users_csv(@userinfocsv)
      end
    end
  end

  #CSVファイルの書込み処理
  private
  def send_users_csv(userinfo)
   csv_data = CSV.generate(encoding: Encoding::SJIS, row_sep: "\r\n", force_quotes: true) do |csv|
      #encoding : utf-8
      header = %w(名前_姓 名前_名 ふりがな_姓_ ふりがな_名_ 性別 生年月日 郵便番号 県 市区町村 番地名 自宅電話 携帯電話 PCメールアドレス 携帯メールアドレス 調査経験回数 交通量調査 走行調査 バス調査 アンケート配布 聞き取り調査 訪問調査 覆面調査_店舗チェック 内勤スタッフ 最寄り事務所 車の所持 最寄り駅 認知経路 認知経路その他 パスワード 登録日時 更新日時)
      csv << header
      userinfo.each do |user|
        values = [
        user.name_first,
        user.name_last,
        user.name_first_read,
        user.name_last_read,
        user.sex,
        user.birthday,
        user.postnumber,
        user.prefecture,
        user.municipalities,
        user.street,
        user.tel_main,
        user.tel_selpfhone,
        user.mail_pc,
        user.mail_pass,
        user.survey_experience,
        user.traffic_survey,
        user.driving_survey,
        user.bus_survey,
        user.questionnaire_distribution,
        user.interview_survey,
        user.visit_survey,
        user.undercover_investigation,
        user.office_staff,
        user.nearest_office,
        user.possession_car,
        user.nearest_station,
        user.cognitive_pathway,
        user.cognitive_pathway_other,
        user.password,
        user.created_at,
        user.updated_at]
        csv << values
      end
    end
    send_data(csv_data, filename: "登録者一覧.csv")
  end

  private
  def admin_user_params
   params.require(:user).permit(:email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  private
   # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update, :destroy]
  def top
    @userinfos = Userinfo.new
  end

  def confirm
    # セッションに保存する
    session[:userinfos] = Userinfo.new(userinfos_params)

    @userinfos = Userinfo.new(userinfos_params)
    render :top if @userinfos.invalid?
  end 

	def back
    params[:userinfo] = session[:userinfos]
		@userinfos = Userinfo.new(userinfos_params)
		render :top
	end

  def create
    params[:userinfo] = session[:userinfos]
    @userinfos = Userinfo.new(userinfos_params)
    if @userinfos.save
      p "会員登録成功！"
    else
      p "会員登録失敗"
    end
    session[:userinfos].clear
  end 

  def userinfos_params
    params.require(:userinfo).permit(:name_first, :name_last, :name_first_read, :name_last_read, :sex, :birthday, :postnumber, :prefecture, :municipalities, :street, :tel_main, :tel_selpfhone, :mail_pc, :mail_pass, :survey_experience, :traffic_survey, :driving_survey, :bus_survey, :questionnaire_distribution, :interview_survey, :visit_survey, :undercover_investigation, :office_staff, :nearest_office, :possession_car, :nearest_station, :cognitive_pathway, :cognitive_pathway_other, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = AdminUser.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to admin_user_path
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to admin_user_path
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
     #@current_user = @current_user || AdminUser.find_by(id: session[:user_id])と同じ意味
      @current_user ||= AdminUser.find_by(id: session[:user_id])
    end
  end
  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/admin_users/new.html.erb
<h1>AdminUsers#new</h1>
<p>Find me in app/views/admin_users/new.html.erb</p>

app/views/admin_users/show.html.erb
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>調査員登録システム・管理画面</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width">
				<!--<script type="text/javascript" src="/0/tyousa_sys/js/footerFixed.js"></script>>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
			<style>
				.digg_pagination {
				background: white;
				cursor: default;
				/* self-clearing method: */ }
				.digg_pagination a, .digg_pagination span, .digg_pagination em {
				padding: 0.2em 0.5em;
				display: block;
				float: left;
				margin-right: 1px; }
				.digg_pagination .disabled {
				color: #999999;
				border: 1px solid #dddddd; }
				.digg_pagination .current {
				font-style: normal;
				font-weight: bold;
				background: #2e6ab1;
				color: white;
				border: 1px solid #2e6ab1; }
				.digg_pagination a {
				text-decoration: none;
				color: #105cb6;
				border: 1px solid #9aafe5; }
				.digg_pagination a:hover, .digg_pagination a:focus {
				color: #000033;
				border-color: #000033; }
				.digg_pagination .page_info {
				background: #2e6ab1;
				color: white;
				padding: 0.4em 0.6em;
				width: 22em;
				margin-bottom: 0.3em;
				text-align: center; }
				.digg_pagination .page_info b {
				color: #000033;
				background: #6aa6ed;
				padding: 0.1em 0.25em; }
				.digg_pagination:after {
				content: ".";
				display: block;
				height: 0;
				clear: both;
				visibility: hidden; }
				* html .digg_pagination {
				height: 1%; }
				*:first-child + html .digg_pagination {
				overflow: hidden;
				}
				h2 {
				float: left;
				width: 94%;
				z-index: 999;
				line-height: 1em;
				}
			</style>
</head>
<body>
	<div id="container">
		<header>
			<h1>ユーザ管理画面</h1>
		</header>
	<div id="contents">
		<h2>
			<%= image_tag 'head_logo.png' %>
		</h2>


			<div class="digg_pagination">
				<%= will_paginate @userinfo, previous_label: '&#8592; &nbsp;前', next_label: '次 &#8594;', inner_window: 1, outer_window: 0 %>
			</div>

		<table class="ta1" border="1" cellpadding="5" width="100%">
			<tbody>
				<tr>
					<th class="abc1">
						お名前
					</th>
					<th class="abc1">
						メールアドレス
					</th>
				</tr>
				<% @userinfo.each do |user| %>
				<tr>
					<td class="abc1">
						<%= user.name_first%>
						<%= user.name_last%>
					</td>
					<td class="abc1">
						<%= user.mail_pc%>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

			<div class="digg_pagination">
				<%= will_paginate @userinfo, previous_label: '&#8592; &nbsp;前', next_label: '次 &#8594;', inner_window: 1, outer_window: 0 %>
			</div>
			<div class="digg_pagination">
				<%= link_to "CSV出力",admin_user_path(format: :csv) %>
			</div>
	
		</div>
</div>
</body>
</html>

app/views/homes/confirm.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>株式会社 丸尾計画事務所</title>
  <meta name="description" content="">
  <meta name="keywords" content="サーベイリサーチセンター,調査員登録システム,交通量調査">
  <meta name="viewport" content="width=device-width">
  <!--<script type="text/javascript" src="/0/tyousa_sys/js/footerFixed.js"></script>>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
  <div id="container">
    <header>
      <h1>株式会社 丸尾計画事務所</h1>
    </header>
    <div id="contents">
      <section>
        <h2>確認画面</h2>
        <div>以下の入力情報で会員登録します。宜しいでしょうか？</div>
        <p>
          <table class="ta1" border="1" cellpadding="5" width="100%">
            <tbody>
              <tr>
                <td class="abc1">姓（漢字）</td>
                <td class="abc2"><%= @userinfos.name_first %></td>
              </tr>
              <tr>
                <td class="abc1">名（漢字）</td>
                <td class="abc2"><%= @userinfos.name_last %></td>
              </tr>
              <tr>
                <td class="abc1">せい（ふりがな）</td>
                <td class="abc2"><%= @userinfos.name_first_read %></td>
              </tr>
              <tr>
                <td class="abc1">めい（ふりがな）</td>
                <td class="abc2"><%= @userinfos.name_last_read %></td>
              </tr>
              <tr>
                <td class="abc1">性別</td>
                <td class="abc2"><div id="sex"></div></td>
              </tr>
              <tr>
                <td class="abc1">生年月日</td>
                <td class="abc2"><%= @userinfos.birthday.strftime("%Y/%m/%d") %></td>
              </tr>
              <tr>
                <td class="abc1">郵便番号</td>
                <td class="abc2"><%= @userinfos.postnumber %></td>
              </tr>
              <tr>
                <td class="abc1">都道府県</td>
                <td class="abc2"><div id="prefecture"></div></td>
              </tr>
              <tr>
                <td class="abc1">市区町村名</td>
                <td class="abc2"><%= @userinfos.municipalities %></td>
              </tr>
              <tr>
                <td class="abc1">番地名</td>
                <td class="abc2"><%= @userinfos.street %></td>
              </tr>
              <tr>
                <td class="abc1">自宅電話番号</td>
                <td class="abc2"><%= @userinfos.tel_main %></td>
              </tr>
              <tr>
                <td class="abc1">携帯電話番号</td>
                <td class="abc2"><%= @userinfos.tel_selpfhone %></td>
              </tr>
              <tr>
                <td class="abc1">PCメールアドレス</td>
                <td class="abc2"><%= @userinfos.mail_pc %></td>
              </tr>
              <tr>
                <td class="abc1">携帯メールアドレス</td>
                <td class="abc2"><%= @userinfos.mail_pass %></td>
              </tr>
              <tr>
                <td class="abc1">調査経験回数</td>
                <td class="abc2"><div id="survey_experience"></div></td>
              </tr>
              <tr>
                <td class="abc1">希望する調査</td>
                <td class="abc2"><div id="desire_survey"></div></td>
              </tr>
              <tr>
                <td class="abc1">最寄丸尾計画事務所</td>
                <td class="abc2"><div id="nearest_office"></div></td>
              </tr>
              <tr>
                <td class="abc1">車の保有について</td>
                <td class="abc2"><div id="possession_car"></div></td>
              </tr>
              <tr>
                <td class="abc1">自宅最寄り駅</td>
                <td class="abc2"><%= @userinfos.nearest_station %></td>
              </tr>
              <tr>
                <td class="abc1">認知経路</td>
                <td class="abc2"><div id="cognitive_pathway"></div></td>
              </tr>
              <tr>
                <td class="abc1">認知経路 その他</td>
                <td class="abc2"><%= @userinfos.cognitive_pathway_other %></td>
              </tr>
              <tr>
                <td class="abc1">パスワード</td>
                <td class="abc2"><%= @userinfos.password %></td>
              </tr>
            </tbody>
          </table>
          <table class="ta1">
            <tbody>
              <tr align="center">
              <%= form_for(@userinfos, url: back_path) do |f| %>
              <td style="width:150px; padding-top:15px; padding-bottom:15px;"><%= f.submit "修正する", style: "width:150px" %></td>
              <% end %>
              <%= form_for(@userinfos, url: create_path) do |f| %>
              <td style="width:150px; padding-top:15px; padding-bottom:15px;"><%= f.submit "登録する", style: "width:150px" %></td>
              <% end %>
              </tr>
            </tbody>
          </table>
        </p>
      </section>
    </div>
    <!--/contents-->
    <div id="footer">
      <footer>
        <font color="white"><small>Copyright&copy; MARUO PLANNING OFFICE CO.,LTD . All Rights Reserved.</small></font>
      </footer>
    </div>
  </div>
  <!--/container-->
<script type="text/javascript">
  //load時に実行する。
  window.onload = function(){
    //性別に文字列をセット
    if("<%= @userinfos.sex %>" == "1"){
      document.getElementById("sex").innerHTML = "男";
    } else {
      document.getElementById("sex").innerHTML = "女";
    }

    //都道府県に文字列をセット
    var prefecture_str;
    switch ("<%= @userinfos.prefecture %>"){
      case "1":
        prefecture_str = "北海道";
        break;
      case "2":
        prefecture_str = "青森県";
        break;
      case "3":
        prefecture_str = "岩手県";
        break;
      case "4":
        prefecture_str = "宮城県";
        break;
      case "5":
        prefecture_str = "秋田県";
        break;
      case "6":
        prefecture_str = "山形県";
        break;
      case "7":
        prefecture_str = "福島県";
        break;
      case "8":
        prefecture_str = "茨城県";
        break;
      case "9":
        prefecture_str = "栃木県";
        break;
      case "10":
        prefecture_str = "群馬県";
        break;
      case "11":
        prefecture_str = "埼玉県";
        break;
      case "12":
        prefecture_str = "千葉県";
        break;
      case "13":
        prefecture_str = "東京都";
        break;
      case "14":
        prefecture_str = "神奈川県";
        break;
      case "15":
        prefecture_str = "新潟県";
        break;
      case "16":
        prefecture_str = "富山県";
        break;
      case "17":
        prefecture_str = "石川県";
        break;
      case "18":
        prefecture_str = "福井県";
        break;
      case "19":
        prefecture_str = "山梨県";
        break;
      case "20":
        prefecture_str = "長野県";
        break;
      case "21":
        prefecture_str = "岐阜県";
        break;
      case "22":
        prefecture_str = "静岡県";
        break;
      case "23":
        prefecture_str = "愛知県";
        break;
      case "24":
        prefecture_str = "三重県";
        break;
      case "25":
        prefecture_str = "滋賀県";
        break;
      case "26":
        prefecture_str = "京都府";
        break;
      case "27":
        prefecture_str = "大阪府";
        break;
      case "28":
        prefecture_str = "兵庫県";
        break;
      case "29":
        prefecture_str = "奈良県";
        break;
      case "30":
        prefecture_str = "和歌山県";
        break;
      case "31":
        prefecture_str = "鳥取県";
        break;
      case "32":
        prefecture_str = "島根県";
        break;
      case "33":
        prefecture_str = "岡山県";
        break;
      case "34":
        prefecture_str = "広島県";
        break;
      case "35":
        prefecture_str = "山口県";
        break;
      case "36":
        prefecture_str = "徳島県";
        break;
      case "37":
        prefecture_str = "香川県";
        break;
      case "38":
        prefecture_str = "愛媛県";
        break;
      case "39":
        prefecture_str = "高知県";
        break;
      case "40":
        prefecture_str = "福岡県";
        break;
      case "41":
        prefecture_str = "佐賀県";
        break;
      case "42":
        prefecture_str = "長崎県";
        break;
      case "43":
        prefecture_str = "熊本県";
        break;
      case "44":
        prefecture_str = "大分県";
        break;
      case "45":
        prefecture_str = "宮崎県";
        break;
      case "46":
        prefecture_str = "鹿児島県";
        break;
      case "47":
        prefecture_str = "沖縄県";
        break;
      default:
    }
    document.getElementById("prefecture").innerHTML = prefecture_str;

    //調査経験回数に文字列をセット
    var survey_experience_str;
    switch ("<%= @userinfos.survey_experience %>"){
      case "1":
        survey_experience_str = "0回";
        break;
      case "2":
        survey_experience_str = "1～5回";
        break;
      case "3":
        survey_experience_str = "6～10回";
        break;
      case "4":
        survey_experience_str = "11回";
        break;
        default:
    }
    document.getElementById("survey_experience").innerHTML = survey_experience_str;

    //希望する調査に文字列をセット
    let desire_survey_str = "";

    if(<%= @userinfos.traffic_survey %>) {desire_survey_str = desire_survey_str + "交通量調査" + '<br>'};
    if(<%= @userinfos.driving_survey %>) {desire_survey_str = desire_survey_str + "走行調査" + '<br>';}
    if(<%= @userinfos.bus_survey %>) {desire_survey_str = desire_survey_str + "バス調査" + '<br>';}
    if(<%= @userinfos.questionnaire_distribution %>) {desire_survey_str = desire_survey_str + "アンケート配布" + '<br>';}
    if(<%= @userinfos.interview_survey %>) {desire_survey_str = desire_survey_str + "聞き取り調査" + '<br>';}
    if(<%= @userinfos.visit_survey %>) {desire_survey_str = desire_survey_str + "訪問調査" + '<br>';}
    if(<%= @userinfos.undercover_investigation %>) {desire_survey_str = desire_survey_str + "覆面調査(店舗チェック)" + '<br>';}
    if(<%= @userinfos.office_staff %>) {desire_survey_str = desire_survey_str + "内勤スタッフ" + '<br>';}

    document.getElementById("desire_survey").innerHTML = desire_survey_str;
  
    //最寄丸尾計画事務所に文字列をセット
    var nearest_office_str;
    switch ("<%= @userinfos.nearest_office %>"){
      case "10":
        nearest_office_str = "兵庫県神戸事務所";
        break;
      case "11":
        nearest_office_str = "大阪事務所";
        break;
      case "2":
        nearest_office_str = "奈良事務所";
        break;
      case "1":
        nearest_office_str = "本社（兵庫県姫路事務所）";
        break;
        default:
    }
    document.getElementById("nearest_office").innerHTML = nearest_office_str;

    //車の保有についてに文字列をセット
    if("<%= @userinfos.possession_car %>" == "1"){
      document.getElementById("possession_car").innerHTML = "はい";
    } else {
      document.getElementById("possession_car").innerHTML = "いいえ";
    }

    //調査経験回数に文字列をセット
    var cognitive_pathway_str;
    switch ("<%= @userinfos.cognitive_pathway %>"){
      case "1":
        cognitive_pathway_str = "調査員説明会";
        break;
      case "2":
        cognitive_pathway_str = "知人の紹介";
        break;
      case "3":
        cognitive_pathway_str = "丸尾計画事務所Webサイト";
        break;
      case "4":
        cognitive_pathway_str = "その他";
        break;
    }
    document.getElementById("cognitive_pathway").innerHTML = cognitive_pathway_str;
  }
</script>
</body>
</html>

app/views/homes/create.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>株式会社 丸尾計画事務所</title>
  <meta name="description" content="">
  <meta name="keywords" content="サーベイリサーチセンター,調査員登録システム,交通量調査">
  <meta name="viewport" content="width=device-width">
  <!--<script type="text/javascript" src="/0/tyousa_sys/js/footerFixed.js"></script>>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
  <div id="container">
    <header>
      <h1>株式会社 丸尾計画事務所</h1>
    </header>
    <div id="contents">
      <section>
        <h2>登録完了画面</h2>
        <p>
          <% if @userinfos.errors.any? %>
        <div class = "errmsg">
        <h3>登録処理でエラーが発生しました。</h3>
        <ul>
          <% @userinfos.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        </div>
        <% end %>
        <% if @userinfos.errors.any? == false %>
          <div>会員情報の登録が完了しました。</div>
        <% end %>
        <div align="center">
        <%= button_to "戻る", {controller: 'homes', action: 'top'}, {method: :get} %>
        <div/>
        </p>
      </section>
    </div>
    <!--/contents-->
    <div id="footer">
      <footer>
        <font color="white"><small>Copyright&copy; 2017 SURVEY RESEARCH CENTER CO., LTD. All Rights Reserved.</small></font>
      </footer>
    </div>
  </div>
  <!--/container-->
<script type="text/javascript">
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adduser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_logged_in.erb
<h1>ログイン成功ですけど</h1>
<table>
    <thead>
      <tr>
        <th>成功です！おめでとう！</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<%= link_to "ログアウト", logout_path, method: :delete %>

app/views/tasks/_not_logged_in.erb
<p>タスクの管理ができるアプリです。まずはログインをしてください。</p>
<%= link_to "ログイン", login_path%>

app/views/tasks/index.html.erb
<h1>TODOアプリ</h1>
<% if logged_in? %>
  <%= render 'tasks/logged_in' %>
<% else %>
  <%= render 'tasks/not_logged_in' %>
<% end %>